services: 
  backend:
    build: ./new-backend
    image: new-backend:latest
    ports:
      - "8001:8001"
    environment:
      MCP_SERVER_URL: "http://host.docker.internal:6277/mcp"
      MCP_DATA_DIR: "/data"
    volumes:
      - vaqa-backend_mcp_data:/vaqa-backend_mcp_data
      - mcp-server-data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
volumes:
  mcp-server-data:
    external: true
  vaqa-backend_mcp_data:
    driver: local
